### ISSUE TITLE
Column width spacing does not account for ANSI color sequences

### ISSUE THREAD

**Issue by wwboynton** [peter-murach/tty-table#6]
To reproduce:

    1.9.3-p392 :038 > p = Pastel.new
    1.9.3-p392 :039 > puts TTY::Table.new(rows:[['test'],['test']],header:[p.green('derp')]).render(:unicode)
    ┌─────────────┐
    │derp         │
    ├─────────────┤
    │test         │
    │test         │
    └─────────────┘

Compare header field width to:

    1.9.3-p392 :042 > puts TTY::Table.new(rows:[['test'],['test']],header:['derp']).render(:unicode)
    ┌────┐
    │derp│
    ├────┤
    │test│
    │test│
    └────┘

**Comment by peter-murach** [comment]
Thanks! The issue reports are very important so please keep them coming. I will definietly fix them. My intention is to release another version of the library this weekend. However, this doesn't mean automatically that everything will be fixed but I believe in incremental delivery and would like you to use the released version as soon as possible so that we can iron everything out.

**Comment by peter-murach** [comment]
Fixed and released as `v0.2.0`!
